jobs:
  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'strimzi_upgrade'
      display_name: 'strimzi-upgrade-bundle'
      profile: 'azp_upgrade'
      cluster_operator_install_type: 'bundle'
      timeout: 360

  - template: '../steps/system_test_general.yaml'
    parameters:
      name: 'kafka_upgrade_downgrade'
      display_name: 'kafka-upgrade-downgrade-bundle'
      profile: 'azp_kafka_upgrade'
      cluster_operator_install_type: 'bundle'
      timeout: 360
