jobs:
  - template: '../../steps/system_test_general.yaml'
    parameters:
      name: 'bridge'
      display_name: 'bridge-bundle'
      profile: 'bridge'
      cluster_operator_install_type: 'bundle'
      timeout: 240
      releaseVersion: '${{ parameters.releaseVersion }}'
