jobs:
  - template: '../../steps/system_test_general.yaml'
    parameters:
      name: 'strimzi_scalability'
      display_name: 'strimzi-scalability-bundle'
      profile: 'azp_scalability'
      cluster_operator_install_type: 'bundle'
      timeout: 360
      releaseVersion: '${{ parameters.releaseVersion }}'
      kafkaVersion: '${{ parameters.kafkaVersion }}'
