# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
prometheus:
  monitor:
    enabled: true
collectors: []
extraArgs:
  - --custom-resource-state-only=true
rbac:
  extraRules:
    - apiGroups:
        - kafka.strimzi.io
      resources:
        - kafkatopics
        - kafkausers
      verbs: [ "list", "watch" ]
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: kafka.strimzi.io
            version: v1beta2
            kind: KafkaTopic
          metricNamePrefix: strimzi_kafka_topic
          metrics:
            - name: "resource_info"
              help: "The current state of a Strimzi kafka topic resource"
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [ metadata, name ]
              labelsFromPath:
                exported_namespace: [ metadata, namespace ]
                partitions: [ spec, partitions ]
                replicas: [ spec, replicas ]
                ready: [ status, conditions, "[type=Ready]", status ]
                generation: [ status, observedGeneration ]
                topicId: [ status, topicId ]
                topicName: [ status, topicName ]
        - groupVersionKind:
            group: kafka.strimzi.io
            version: v1beta2
            kind: KafkaUser
          metricNamePrefix: strimzi_kafka_user
          metrics:
            - name: "resource_info"
              help: "The current state of a Strimzi kafka user resource"
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [ metadata, name ]
              labelsFromPath:
                exported_namespace: [ metadata, namespace ]
                ready: [ status, conditions, "[type=Ready]", status ]
                deprecated: [ status, conditions, "[reason=DeprecatedFields]", type ]
                secret: [ status, secret ]
                generation: [ status, observedGeneration ]
                username: [ status, username ]
extraManifests:
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: strimzi-kube-state-metrics
    spec:
      groups:
        - name: strimzi-kube-state-metrics
          rules:
            - alert: KafkaUserDeprecated
              expr: strimzi_kafka_user_resource_info{deprecated="Warning"}
              for: 15m
              labels:
                severity: warning
              annotations:
                message: 'Strimzi Kafka User {{`{{ $labels.username }}`}} has a deprecated configuration'
            - alert: KafkaUserNotReady
              expr: strimzi_kafka_user_resource_info{ready!="True"}
              for: 15m
              labels:
                severity: warning
              annotations:
                message: 'Strimzi Kafka User {{`{{ $labels.username }}`}} is not ready'
            - alert: KafkaTopicNotReady
              expr: strimzi_kafka_topic_resource_info{ready!="True"}
              for: 15m
              labels:
                severity: warning
              annotations:
                message: 'Strimzi Kafka Topic {{`{{ $labels.topicName }}`}} is not ready'
