# Triggers
# This pipeline will be triggered manually for a release or by github comment
trigger: none
pr:
  autoCancel: false
  branches:
    include:
      - '*'

stages:
  - stage: "acceptance"
    dependsOn: []
    jobs:
      - template: 'templates/jobs/system-tests/acceptance_helm_jobs.yaml'

      - template: 'templates/jobs/system-tests/acceptance_helm_namespace_rbac_jobs.yaml'

      - template: 'templates/jobs/system-tests/acceptance_jobs.yaml'

  - stage: "upgrade"
    dependsOn: []
    jobs:
      - template: 'templates/jobs/system-tests/upgrade_jobs.yaml'

  - stage: "regression"
    dependsOn: [ "acceptance","upgrade" ]
    jobs:
      - template: "templates/jobs/system-tests/regression_jobs.yaml"

  - stage: "regression_feature_gates"
    dependsOn: [ "acceptance","regression","upgrade" ]
    condition: succeeded('acceptance','upgrade','regression')
    jobs:
      - template: "templates/jobs/system-tests/feature_gates_regression_jobs.yaml"

  - stage: "regression_namespace_rbac"
    dependsOn: [ "acceptance","regression","upgrade","regression_feature_gates" ]
    condition: succeeded('acceptance','upgrade','regression','regression_feature_gates')
    jobs:
      - template: "templates/jobs/system-tests/regression_namespace_rbac_jobs.yaml"
