{{- if .Values.serviceAccountCreate -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccountAnnotations }}
  annotations:
    {{- range $key, $value := .Values.serviceAccountAnnotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ template "strimzi.name" . }}
    chart: {{ template "strimzi.chart" . }}
    component: service-account
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}